# Digital Test Board

* Board Info

** DTB 40 
   <2014-02-05 Wed> Took from Kirk's office, with initial label "OLD
   FIRMWARE". Now in PHYS 347. 
   Updated the firmware to 1.17. 
   
   
** DTB 47 

   <2014-02-13 Thu> Took from PHYS360 to PHYS347.
   Flashed with v1.25 using JTAG. 

   <2014-01-15 Wed> 
   Connected with purduepix-Inspiron-660 (rename it to pupx1). 

   Noticed the four LED's labeled 1 through 4 DOES NOT show a moving pattern!

   Try to test with psi46test:
   : PSI46V2 ROC/Wafer Tester V1.3 (07.08.2013)
   : void Init();
   : ERROR: READ_ERROR

   Returned to Mayur at PHYS360. Labeled "BAD FIRMWARE". 

   <2014-01-14 Tue> Got from PHYS 360 with board and connector. 


** DTB 48 
   
   <2014-02-04 Tue> Flashed with 1.16 for HDI reception test. 
   
   <2014-01-29 Wed> Flash with 1.17 with JTAG... with error. 
   Found twiki:
   http://www.alterawiki.com/wiki/Quartus_for_Linux#Setup_JTAG
   
   http://www.ict.kth.se/courses/IS1200/2008-2009/nios2setup/linux.html
   
   <2014-01-17 Fri> Flashed with 1.14. 

   <2014-01-15 Wed> Connected with pupx1, noticed the four LEDs moving pattern. 

   Passed the psi46test:

 : PSI46V2 ROC/Wafer Tester V1.3 (07.08.2013)
 : 
 : DTB DTB_WRMT3D opened
 : --- DTB info-------------------------------------
 : Board id:    48
 : HW version:  DTB1.2
 : FW version:  1.1
 : SW version:  1.7
 : USB id:      DTB_WRMT3D
 : MAC address: 40D855118030
 : Hostname:    pixelDTB048
 : Comment:     
 : -------------------------------------------------
 : 
 : +-- control commands ------------------------------------------+
 : | h                  display this text                         |
 : | exit               exit commander                            |
 : +-- chip test -------------------------------------------------+
 : | test <chip id>     run chip test                             |
 : +--------------------------------------------------------------+
   
   Try with pxar:

   [10:55:07.758] ERROR: RPC Call count of DTB and host do not match.

   Update the FW to 1.13, according to [[https://twiki.cern.ch/twiki/bin/view/CMS/PixelDTB][PixelDTB]]. 
   
   DTB DTB_WRMT3D opened
   --- DTB info-------------------------------------
   Board id:    48
   HW version:  DTB1.2
   FW version:  1.2
   SW version:  1.13
   USB id:      DTB_WRMT3D
   MAC address: 40D855118030
   Hostname:    pixelDTB048

   Try again with pxar: still problem. 

   Got info from Simon, need to use the file at: 
   https://twiki.cern.ch/twiki/bin/view/CMS/Pxar
   
   Can see the pXar GUI now! 
   
   <2014-01-14 Tue> Introduced by Kirk in PHYS347. 

