.TH drawMod 1 "4 December 2014" CMSPXL "User Manuals"
.SH NAME
drawMod \- draw Module plots
.SH SYNOPSIS
.B drawMod [-i 
.I input-file
.B ] 
.B [-g] [-t 
.I testname
.B ] [-draw 
.I draw-option
.B ] [-vmin 
.I vmin-value
.B ]
.B ] [-vmax 
.I vmax-value
.B ]
.SH DESCRIPTION
.B drawMod 
Draw Modul curves based on root files. 
.SH OPTIONS
.IP -i 
Input file 
.IP -g 
Run GUI
.IP -t 
test name [pretest, pixelalive, bumpbonding, daq]
.IP -v 
version number for output file 
.IP -draw
draw option for histogram [colz, surf2]
.IP -vmin 
limit the histogram within vmin-value 
.IP -vmax 
limit the histogram within vmax-value 
.SH AUTHOR
Xin Shi <Xin.Shi@cern.ch>
